// src-tauri/src/crypto/signed_message/tests.rs
//
//! Tests for the Dash Signed Message implementation.
//!
//! The hash vectors below were produced by an INDEPENDENT reference
//! implementation of `evonext-api/src/libs/verifySignature.ts`'s
//! `hashMessage()` (plain Node `crypto`, transcribed from the TS). They are
//! NOT generated by the Rust code under test — that is the whole point: if
//! the two ever diverge, these tests fail, and push registration would
//! silently stop verifying.

use super::*;

/// Vector 1 — a realistic `push_register` canonical message.
/// Generated by the reference implementation of verifySignature.ts.
const CANONICAL_MSG: &str = "action:push_register\nidentityId:ADtgYG2MHikwv4UiZeY8faUsEkH1YDjEnJFhGbuXLfFB\ndeviceToken:abc123def456\ntimestamp:1789835811";
const CANONICAL_HASH: &str = "d532bb487e9e360e84a8b8a47a9d0d8a34ee3958b3df7058e115eb16157cc230";

#[test]
fn test_dash_message_hash_matches_reference_for_canonical_message() {
    let hash = dash_message_hash(CANONICAL_MSG).expect("hash must succeed");
    assert_eq!(
        hex::encode(hash),
        CANONICAL_HASH,
        "Rust hash diverged from verifySignature.ts — push registration would fail server-side"
    );
}

#[test]
fn test_magic_prefix_byte_is_the_spec_constant_not_the_string_length() {
    // Regression guard for a real bug caught by these very vectors: the
    // prefix byte is 0x19 (25) per the Dash spec, while the magic STRING is
    // only 21 bytes. Deriving the prefix from `.len()` produces a digest the
    // server will never accept. Assert the constant explicitly so nobody
    // "simplifies" it back to a computed length.
    assert_eq!(DASH_MESSAGE_MAGIC.len(), 21, "magic string is 21 bytes");
    assert_eq!(DASH_MESSAGE_PREFIX_LEN, 0x19, "prefix is 25, not 21");
    assert_ne!(
        DASH_MESSAGE_PREFIX_LEN as usize,
        DASH_MESSAGE_MAGIC.len(),
        "prefix must NOT equal the magic string length"
    );
}

#[test]
fn test_dash_message_hash_matches_reference_for_short_message() {
    // Vector 2 — "hello".
    let hash = dash_message_hash("hello").expect("hash must succeed");
    assert_eq!(
        hex::encode(hash),
        "ae22bc3745447e45f00223265b4d3f2498a62bb93850f9e93d8485bccc69dee8"
    );
}

#[test]
fn test_dash_message_hash_matches_reference_for_empty_message() {
    // Vector 3 — empty string still carries both length prefixes.
    let hash = dash_message_hash("").expect("hash must succeed");
    assert_eq!(
        hex::encode(hash),
        "abeb565b29b38fa086c8551cd58cc5c5c1ce0d2380dc4137f33ef720786c4845"
    );
}

#[test]
fn test_dash_message_hash_matches_reference_at_255_byte_ceiling() {
    // Vector 4 — the documented maximum (single-byte length prefix).
    let msg = "a".repeat(255);
    let hash = dash_message_hash(&msg).expect("255 bytes must be allowed");
    assert_eq!(
        hex::encode(hash),
        "5e84bbf521ca88a02947e2ce334bff8ec4300567f4bd0791625575b3488e9990"
    );
}

#[test]
fn test_dash_message_hash_rejects_messages_over_255_bytes() {
    // 256 bytes would wrap the single-byte length prefix and collide with
    // a shorter message. Must be refused, not silently truncated.
    let msg = "a".repeat(256);
    let err = dash_message_hash(&msg).expect_err("256 bytes must be rejected");
    assert_eq!(err, SignedMessageError::MessageTooLong(256));
}

#[test]
fn test_build_canonical_message_matches_mobile_and_server_layout() {
    // Field order and separators must match buildCanonicalMessage in BOTH
    // PushRegistrationService.ts and verifySignature.ts.
    let msg = build_canonical_message(
        "push_register",
        "ADtgYG2MHikwv4UiZeY8faUsEkH1YDjEnJFhGbuXLfFB",
        "abc123def456",
        1789835811,
    );
    assert_eq!(msg, CANONICAL_MSG);

    // Exact line order.
    let lines: Vec<&str> = msg.split('\n').collect();
    assert_eq!(lines.len(), 4);
    assert!(lines[0].starts_with("action:"));
    assert!(lines[1].starts_with("identityId:"));
    assert!(lines[2].starts_with("deviceToken:"));
    assert!(lines[3].starts_with("timestamp:"));
}

#[test]
fn test_canonical_message_hash_is_stable_through_builder() {
    // End-to-end: builder -> hash must equal the transport-level vector.
    let msg = build_canonical_message(
        "push_register",
        "ADtgYG2MHikwv4UiZeY8faUsEkH1YDjEnJFhGbuXLfFB",
        "abc123def456",
        1789835811,
    );
    let hash = dash_message_hash(&msg).expect("hash must succeed");
    assert_eq!(hex::encode(hash), CANONICAL_HASH);
}

// ---------------------------------------------------------------- signing

/// Deterministic test key (NOT a real wallet).
fn test_key() -> [u8; 32] {
    let mut k = [0u8; 32];
    for (i, b) in k.iter_mut().enumerate() {
        *b = (i as u8) + 1;
    }
    k
}

#[test]
fn test_sign_then_verify_roundtrip() {
    let key = test_key();
    let hash = dash_message_hash(CANONICAL_MSG).expect("hash");
    let sig = sign_hash(&key, &hash).expect("sign");

    // Derive the public key and verify.
    use k256::ecdsa::SigningKey;
    let sk = SigningKey::from_bytes((&key).into()).expect("key");
    let vk = sk.verifying_key();
    let pubkey = vk.to_encoded_point(true).as_bytes().to_vec();

    verify_hash(&hash, &sig, &pubkey).expect("signature must verify");
}

#[test]
fn test_verify_rejects_tampered_signature() {
    let key = test_key();
    let hash = dash_message_hash(CANONICAL_MSG).expect("hash");
    let mut sig = sign_hash(&key, &hash).expect("sign");

    // Flip a bit in r.
    sig[0] ^= 0x01;

    use k256::ecdsa::SigningKey;
    let sk = SigningKey::from_bytes((&key).into()).expect("key");
    let pubkey = sk
        .verifying_key()
        .to_encoded_point(true)
        .as_bytes()
        .to_vec();

    assert!(verify_hash(&hash, &sig, &pubkey).is_err());
}

#[test]
fn test_verify_rejects_wrong_message() {
    let key = test_key();
    let hash = dash_message_hash(CANONICAL_MSG).expect("hash");
    let sig = sign_hash(&key, &hash).expect("sign");

    use k256::ecdsa::SigningKey;
    let sk = SigningKey::from_bytes((&key).into()).expect("key");
    let pubkey = sk
        .verifying_key()
        .to_encoded_point(true)
        .as_bytes()
        .to_vec();

    let other_hash = dash_message_hash("different").expect("hash");
    assert!(verify_hash(&other_hash, &sig, &pubkey).is_err());
}

#[test]
fn test_verify_rejects_wrong_public_key() {
    let key = test_key();
    let hash = dash_message_hash(CANONICAL_MSG).expect("hash");
    let sig = sign_hash(&key, &hash).expect("sign");

    // A different key's public key must not verify.
    let mut other = test_key();
    other[0] ^= 0xff;
    use k256::ecdsa::SigningKey;
    let sk = SigningKey::from_bytes((&other).into()).expect("key");
    let pubkey = sk
        .verifying_key()
        .to_encoded_point(true)
        .as_bytes()
        .to_vec();

    assert_eq!(
        verify_hash(&hash, &sig, &pubkey),
        Err(SignedMessageError::VerificationFailed)
    );
}

#[test]
fn test_sign_message_base64_produces_65_byte_decodable_signature() {
    use base64::Engine;
    let key = test_key();
    let b64 = sign_message_base64(&key, CANONICAL_MSG).expect("sign");

    let raw = base64::engine::general_purpose::STANDARD
        .decode(&b64)
        .expect("must be valid base64");
    assert_eq!(raw.len(), 65, "compact recoverable signature is 65 bytes");
    assert!(raw[64] <= 3, "recovery id must be 0..=3");
}

#[test]
fn test_signing_is_deterministic_for_same_input() {
    // k256 uses RFC6979 deterministic ECDSA, so the same key+hash must
    // always yield the same signature. If this ever fails, something has
    // switched to a random nonce and device tokens would be non-reproducible.
    let key = test_key();
    let a = sign_message_base64(&key, CANONICAL_MSG).expect("sign");
    let b = sign_message_base64(&key, CANONICAL_MSG).expect("sign");
    assert_eq!(a, b);
}

// -------------------------------------------------------------- ws_connect

/// Independent reference vector for the WebSocket handshake message,
/// generated by a Node transcription of the ws_connect builder. Same
/// discipline as the push vectors above: NOT produced by the Rust code under
/// test, so a divergence fails the build instead of shipping.
const WS_CANONICAL_MSG: &str = "action:ws_connect\nidentityId:ADtgYG2MHikwv4UiZeY8faUsEkH1YDjEnJFhGbuXLfFB\nsessionId:sess-9f3a1c7e-2b44-4d10-9a88-7c5e1f2ab0d3\ntimestamp:1789835811";
const WS_CANONICAL_HASH: &str = "ab99b5708e5ecc05ec135f60902262ce5c07227e4f0f4de4e5802a1e6d4e32c8";

#[test]
fn test_build_ws_canonical_message_matches_reference_layout() {
    let msg = build_ws_canonical_message(
        "ADtgYG2MHikwv4UiZeY8faUsEkH1YDjEnJFhGbuXLfFB",
        "sess-9f3a1c7e-2b44-4d10-9a88-7c5e1f2ab0d3",
        1789835811,
    );
    assert_eq!(msg, WS_CANONICAL_MSG);

    // Exact line order — the server reconstructs this string independently,
    // so a reordering here silently breaks every handshake.
    let lines: Vec<&str> = msg.split('\n').collect();
    assert_eq!(lines.len(), 4);
    assert_eq!(lines[0], "action:ws_connect");
    assert!(lines[1].starts_with("identityId:"));
    assert!(lines[2].starts_with("sessionId:"));
    assert!(lines[3].starts_with("timestamp:"));
}

#[test]
fn test_ws_canonical_message_hash_matches_reference() {
    let msg = build_ws_canonical_message(
        "ADtgYG2MHikwv4UiZeY8faUsEkH1YDjEnJFhGbuXLfFB",
        "sess-9f3a1c7e-2b44-4d10-9a88-7c5e1f2ab0d3",
        1789835811,
    );
    let hash = dash_message_hash(&msg).expect("hash must succeed");
    assert_eq!(hex::encode(hash), WS_CANONICAL_HASH);
}

#[test]
fn test_ws_and_push_canonical_messages_are_distinct() {
    // An action-confusion guard: if ws_connect ever produced the same bytes
    // as push_register, a captured push signature would be replayable as a
    // socket handshake (and vice versa).
    let ws = build_ws_canonical_message("ID", "sess", 1789835811);
    let push = build_canonical_message("push_register", "ID", "sess", 1789835811);
    assert_ne!(ws, push);
    assert!(ws.starts_with("action:ws_connect\n"));
    assert!(push.starts_with("action:push_register\n"));
}

#[test]
fn test_ws_connect_action_constant_is_the_wire_value() {
    // Pinned so a rename cannot silently change the signed payload.
    assert_eq!(WS_CONNECT_ACTION, "ws_connect");
    assert!(build_ws_canonical_message("A", "B", 0).contains("action:ws_connect"));
}

#[test]
fn test_ws_canonical_message_is_within_single_byte_prefix_ceiling() {
    // Realistic worst case: 44-char identity + 36-char UUID session + 10-digit
    // timestamp must stay under 255 bytes or dash_message_hash would refuse.
    let msg = build_ws_canonical_message(&"A".repeat(44), &"b".repeat(36), 9999999999);
    assert!(
        msg.len() <= MAX_SIGNED_MESSAGE_LEN,
        "ws handshake message is {} bytes, over the {} ceiling",
        msg.len(),
        MAX_SIGNED_MESSAGE_LEN
    );
    assert!(dash_message_hash(&msg).is_ok());
}

#[test]
fn test_ws_handshake_signs_and_verifies_end_to_end() {
    // The full client path: build -> hash -> sign -> verify, mirroring what
    // the Rust socket client will do with a vault key and the server will
    // check against the identity's public keys.
    use k256::ecdsa::SigningKey;

    let key = test_key();
    let msg = build_ws_canonical_message(
        "ADtgYG2MHikwv4UiZeY8faUsEkH1YDjEnJFhGbuXLfFB",
        "sess-9f3a1c7e-2b44-4d10-9a88-7c5e1f2ab0d3",
        1789835811,
    );
    let b64 = sign_message_base64(&key, &msg).expect("sign");

    let hash = dash_message_hash(&msg).expect("hash");
    let sk = SigningKey::from_bytes((&key).into()).expect("key");
    let pubkey = sk
        .verifying_key()
        .to_encoded_point(true)
        .as_bytes()
        .to_vec();

    let sig_bytes = {
        use base64::Engine;
        base64::engine::general_purpose::STANDARD
            .decode(&b64)
            .expect("b64")
    };
    let mut sig = [0u8; 65];
    sig.copy_from_slice(&sig_bytes);

    verify_hash(&hash, &sig, &pubkey).expect("ws handshake must verify");
}

// -------------------------------------------------------------------- WIF

#[test]
fn test_decode_wif_accepts_compressed_and_uncompressed() {
    // Known-good WIFs generated from 32 bytes of 0x01.
    let key_bytes = [1u8; 32];
    use bitcoin::base58;

    // Compressed: 0x80 || key || 0x01
    let mut compressed = vec![0x80u8];
    compressed.extend_from_slice(&key_bytes);
    compressed.push(0x01);
    let wif_c = base58::encode_check(&compressed);

    // Uncompressed: 0x80 || key
    let mut uncompressed = vec![0x80u8];
    uncompressed.extend_from_slice(&key_bytes);
    let wif_u = base58::encode_check(&uncompressed);

    assert_eq!(decode_wif(&wif_c).expect("compressed"), key_bytes);
    assert_eq!(decode_wif(&wif_u).expect("uncompressed"), key_bytes);
}

#[test]
fn test_decode_wif_rejects_bad_checksum() {
    let mut wif = {
        use bitcoin::base58;
        let mut b = vec![0x80u8];
        b.extend_from_slice(&[1u8; 32]);
        b.push(0x01);
        base58::encode_check(&b)
    };
    // Corrupt the final character.
    let last = wif.pop().expect("non-empty");
    wif.push(if last == 'a' { 'b' } else { 'a' });

    assert!(decode_wif(&wif).is_err(), "bad checksum must be rejected");
}

#[test]
fn test_decode_wif_rejects_wrong_version_byte() {
    use bitcoin::base58;
    let mut b = vec![0x81u8]; // wrong version
    b.extend_from_slice(&[1u8; 32]);
    b.push(0x01);
    let wif = base58::encode_check(&b);

    match decode_wif(&wif) {
        Err(SignedMessageError::BadPublicKey(_)) => {}
        other => panic!("expected BadPublicKey, got {other:?}"),
    }
}

#[test]
fn test_decode_wif_accepts_testnet_version_byte() {
    // REGRESSION (found 2026-09-20): testnet WIFs carry version byte 0xef,
    // not 0x80. The original implementation hardcoded 0x80, so EVERY WIF
    // this app actually stores on the default network was rejected.
    //
    // Why this went unnoticed: the only unit tests built their fixtures with
    // a hardcoded 0x80 (see `test_wif()` in `realtime/register.rs`, which
    // asserts "decode_wif rejects ... testnet (0xef)" as if that were
    // correct). The real keystore holds `c...` WIFs, i.e. 0xef.
    //
    // Observable consequence before the fix: `register_realtime_device`
    // always returned `registered: false, detail: "invalid WIF: unexpected
    // WIF version byte 0xef"`, and the WebSocket handshake could never be
    // signed, so `build_authenticated_url` returned None and the client
    // exited immediately with no socket and no error visible to the user.
    use bitcoin::base58;

    let key_bytes = [7u8; 32];

    // Testnet compressed: 0xef || key || 0x01
    let mut compressed = vec![0xefu8];
    compressed.extend_from_slice(&key_bytes);
    compressed.push(0x01);
    let wif_c = base58::encode_check(&compressed);

    // Testnet uncompressed: 0xef || key
    let mut uncompressed = vec![0xefu8];
    uncompressed.extend_from_slice(&key_bytes);
    let wif_u = base58::encode_check(&uncompressed);

    assert_eq!(decode_wif(&wif_c).expect("testnet compressed"), key_bytes);
    assert_eq!(decode_wif(&wif_u).expect("testnet uncompressed"), key_bytes);
}

#[test]
fn test_decode_wif_testnet_and_mainnet_yield_the_same_key_material() {
    // The version byte is a network marker, NOT part of the key. The same
    // 32 bytes encoded for either network must decode identically, otherwise
    // a signature would differ by network for the same identity key.
    use bitcoin::base58;

    let key_bytes = {
        let mut k = [0u8; 32];
        k[31] = 99;
        k
    };

    let mut mainnet = vec![0x80u8];
    mainnet.extend_from_slice(&key_bytes);
    mainnet.push(0x01);

    let mut testnet = vec![0xefu8];
    testnet.extend_from_slice(&key_bytes);
    testnet.push(0x01);

    let from_mainnet = decode_wif(&base58::encode_check(&mainnet)).expect("mainnet");
    let from_testnet = decode_wif(&base58::encode_check(&testnet)).expect("testnet");

    assert_eq!(from_mainnet, from_testnet);
    assert_eq!(from_testnet, key_bytes);
}

#[test]
fn test_decode_wif_rejects_an_unrelated_version_byte() {
    // Widening the accepted set must not make the check meaningless: any
    // version byte that is neither mainnet nor testnet is still rejected.
    use bitcoin::base58;

    for version in [0x00u8, 0x01, 0x05, 0x81, 0xee, 0xf0] {
        let mut b = vec![version];
        b.extend_from_slice(&[1u8; 32]);
        b.push(0x01);
        let wif = base58::encode_check(&b);

        assert!(
            decode_wif(&wif).is_err(),
            "version byte 0x{version:02x} must be rejected"
        );
    }
}

#[test]
fn test_decode_wif_rejects_garbage() {
    assert!(decode_wif("not-a-wif").is_err());
    assert!(decode_wif("").is_err());
}

#[test]
fn test_decode_wif_roundtrips_through_signing() {
    // Full path: WIF -> key -> sign -> verify. This is exactly what the
    // push registration flow will do with a vault-stored key.
    use bitcoin::base58;
    use k256::ecdsa::SigningKey;

    let key_bytes = {
        let mut k = [0u8; 32];
        k[31] = 42;
        k
    };
    let mut raw = vec![0x80u8];
    raw.extend_from_slice(&key_bytes);
    raw.push(0x01);
    let wif = base58::encode_check(&raw);

    let decoded = decode_wif(&wif).expect("decode");
    let b64 = sign_message_base64(&decoded, CANONICAL_MSG).expect("sign");

    // Verify with the public key derived from the same key material.
    let sk = SigningKey::from_bytes((&decoded).into()).expect("key");
    let pubkey = sk
        .verifying_key()
        .to_encoded_point(true)
        .as_bytes()
        .to_vec();
    let hash = dash_message_hash(CANONICAL_MSG).expect("hash");
    let sig_bytes = {
        use base64::Engine;
        base64::engine::general_purpose::STANDARD
            .decode(&b64)
            .expect("b64")
    };
    let mut sig = [0u8; 65];
    sig.copy_from_slice(&sig_bytes);

    verify_hash(&hash, &sig, &pubkey).expect("must verify");
}
