// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveIdentityPayload = { identityId: string, identityIdx: number | null, username: string | null, dpnsUsername: string | null, balance: string | null, revision: unknown, publicKeys: unknown[], createdAt: string | null, activeIdentityId: string | null, };
