// src/stores/identity/state.ts

import type { IIdentityState, IIdentity, IPublicKey, DiscoveryProgress } from '@/types/identity'
export const useIdentityState = (): IIdentityState => ({
    identityId: null,
    identityIdx: 0,
    username: null,
    displayName: "",
    identity: null,
    identities: {} as Record<string, IIdentity>,
    balance: '0',
    formattedBalance: '0.00 DASH',
    balanceBigInt: BigInt(0),
    dashBigInt: BigInt(0),
    publicKeys: [] as IPublicKey[],
    revision: 0,
    isAuthenticated: false,
    isConnected: false,
    isConnecting: false,
    premiumAccess: false,
    connectionError: null,
    discoveryProgress: null as DiscoveryProgress | null,
    // Actions mapped as empty stubs for the state definition
    connectWithSeed: async () => ({ success: false }),
    connectWithPrivateKey: async () => ({ success: false }),
    connectWriteOnlyFromDiscovered: async () => ({ success: false }),
    refreshIdentity: async () => {},
    fetchBalance: async () => {},
    loadPublicKeys: async () => [],
    // Added to satisfy IIdentityActions interface
    getPublicKeys: async (_id: string, _net: string) => ({ success: false, data: null }),
    switchIdentity: async () => {},
    deleteIdentity: async () => {},
    updateIdentityMetadata: async () => {},
    searchUserIdentities: async () => [],
    loadFromStorage: async () => {},
    saveToStorage: async () => {},
    clearStorage: async () => {},
    clearConnectionError: () => {},
    saveKeys: async () => {},
    saveMnemonicToStore: async () => {},
    saveIdentityDataToStore: async () => {},
    getCurrentNetwork: async () => 'testnet',
    loadKeystore: async () => null,
})
