// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UnifiedCommandResult = { success: boolean, error: string | null, payload: unknown, };
