//@ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async discoverAssets(identityId: string, network: string) : Promise<ICommandResult<IAssetDefinition[]>> {
    return await TAURI_INVOKE("discover_assets", { identityId, network });
},
async fetchIdentityTokens(identityId: string, network: string) : Promise<ICommandResult<IAssetDefinition[]>> {
    return await TAURI_INVOKE("fetch_identity_tokens", { identityId, network });
},
async loadAssets(identityId: string, network: string) : Promise<ICommandResult<IAssetDefinition[]>> {
    return await TAURI_INVOKE("load_assets", { identityId, network });
},
async saveAssets(identityId: string, network: string, payload: IAssetDefinition[]) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("save_assets", { identityId, network, payload });
},
async deleteAssets(network: string) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("delete_assets", { network });
},
async hash160(input: number[]) : Promise<ICommandResult<number[]>> {
    return await TAURI_INVOKE("hash160", { input });
},
async randomBytes(len: number) : Promise<ICommandResult<number[]>> {
    return await TAURI_INVOKE("random_bytes", { len });
},
async saveIdentity(network: string, payload: ISaveIdentityPayload) : Promise<ICommandResult<IUnifiedCommandResult>> {
    return await TAURI_INVOKE("save_identity", { network, payload });
},
async saveIdentityWithKeys(network: string, identityPayload: ISaveIdentityPayload, keys: IPrivateKeyEntry[]) : Promise<ICommandResult<IUnifiedCommandResult>> {
    return await TAURI_INVOKE("save_identity_with_keys", { network, identityPayload, keys });
},
async discoverAndSaveIdentity(identityId: string, network: string) : Promise<ICommandResult<IUnifiedCommandResult>> {
    return await TAURI_INVOKE("discover_and_save_identity", { identityId, network });
},
async deleteIdentity(network: string, identityId: string | null) : Promise<ICommandResult<boolean>> {
    return await TAURI_INVOKE("delete_identity", { network, identityId });
},
async saveKeys(network: string, identityId: string, keys: IPrivateKeyEntry[]) : Promise<ICommandResult<boolean>> {
    return await TAURI_INVOKE("save_keys", { network, identityId, keys });
},
async loadKeystore(network: string) : Promise<ICommandResult<any>> {
    return await TAURI_INVOKE("load_keystore", { network });
},
/**
 * Load the active identity for a given network.
 * Returns the active identity ID, the identity data (if found), and total count.
 * This is the primary command used by the frontend to restore session on app reload.
 */
async loadActiveIdentity(network: string) : Promise<ICommandResult<IActiveIdentityResponse>> {
    return await TAURI_INVOKE("load_active_identity", { network });
},
/**
 * Load all identities for a given network.
 * Returns the raw identity map as a JSON value for the Identity Manager screen.
 */
async loadIdentitiesMap(network: string) : Promise<ICommandResult<any>> {
    return await TAURI_INVOKE("load_identities_map", { network });
},
async loadLicense(identityId: string) : Promise<ICommandResult<ILicense | null>> {
    return await TAURI_INVOKE("load_license", { identityId });
},
async saveLicense(payload: ILicense) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("save_license", { payload });
},
async deleteLicense(identityId: string) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("delete_license", { identityId });
},
async refreshLicense(identityId: string) : Promise<ICommandResult<ILicense>> {
    return await TAURI_INVOKE("refresh_license", { identityId });
},
async loadMnemonic(network: string) : Promise<ICommandResult<IMnemonic | null>> {
    return await TAURI_INVOKE("load_mnemonic", { network });
},
async saveMnemonic(network: string, payload: IMnemonic) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("save_mnemonic", { network, payload });
},
async deleteMnemonic(network: string) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("delete_mnemonic", { network });
},
async loadSettings() : Promise<ICommandResult<IAppSettings | null>> {
    return await TAURI_INVOKE("load_settings");
},
async saveSettings(settings: IAppSettings) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("save_settings", { settings });
},
async deleteSettings() : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("delete_settings");
},
async updateIdentityWithSdkData(network: string, identityId: string, publicKeys: IIdentityPublicKey[], revision: number, publicKeyIds: number[]) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("update_identity_with_sdk_data", { network, identityId, publicKeys, revision, publicKeyIds });
},
async getIdentityPublicKeys(network: string, identityId: string) : Promise<ICommandResult<IIdentityPublicKey[] | null>> {
    return await TAURI_INVOKE("get_identity_public_keys", { network, identityId });
},
async deleteIdentityPublicKeys(network: string, identityId: string) : Promise<ICommandResult<null>> {
    return await TAURI_INVOKE("delete_identity_public_keys", { network, identityId });
},
async dapiRequest(method: string, params: Partial<{ [key in string]: JsonValue }>, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("dapi_request", { method, params, network });
},
async dapiRequestArray(method: string, paramsArray: JsonValue[], network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("dapi_request_array", { method, paramsArray, network });
},
async getPosts(dataContractId: string, documentType: string, whereClause: JsonValue | null, orderBy: JsonValue | null, limit: number | null, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_posts", { dataContractId, documentType, whereClause, orderBy, limit, network });
},
async getIdentityInfo(identityId: string, network: string | null) : Promise<ICommandResult<DapiIdentityResponse>> {
    return await TAURI_INVOKE("get_identity_info", { identityId, network });
},
async getIdentityBalance(identityId: string, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_identity_balance", { identityId, network });
},
async getIdentityById(identityId: string, network: string | null) : Promise<ICommandResult<JsonValue>> {
    return await TAURI_INVOKE("get_identity_by_id", { identityId, network });
},
async getTokenBalances(identityId: string, tokenIds: string[], network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_token_balances", { identityId, tokenIds, network });
},
async resolveDpnsName(username: string, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("resolve_dpns_name", { username, network });
},
async getDpnsUsername(identityId: string, network: string | null) : Promise<ICommandResult<string | null>> {
    return await TAURI_INVOKE("get_dpns_username", { identityId, network });
},
async getDpnsUsernames(identityId: string, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_dpns_usernames", { identityId, network });
},
async getPlatformStatus(network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_platform_status", { network });
},
async getIdentitiesBalances(identityIds: string[], network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_identities_balances", { identityIds, network });
},
async getDataContractInfo(contractId: string, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_data_contract_info", { contractId, network });
},
async getTokenContractInfo(contractId: string, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_token_contract_info", { contractId, network });
},
async getTokenStatuses(tokenIds: string[], network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_token_statuses", { tokenIds, network });
},
async getTotalSupply(tokenId: string, network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_total_supply", { tokenId, network });
},
async getCurrentEpoch(network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_current_epoch", { network });
},
async getTotalCreditsInPlatform(network: string | null) : Promise<ICommandResult<JsonValue[]>> {
    return await TAURI_INVOKE("get_total_credits_in_platform", { network });
},
async getIdentityByPublicKeyHash(publicKeyHash: string, network: string | null) : Promise<ICommandResult<DapiIdentityResponse>> {
    return await TAURI_INVOKE("get_identity_by_public_key_hash", { publicKeyHash, network });
},
async getIdentityByNonUniquePublicKeyHash(publicKeyHash: string, network: string | null) : Promise<ICommandResult<DapiIdentityResponse>> {
    return await TAURI_INVOKE("get_identity_by_non_unique_public_key_hash", { publicKeyHash, network });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Represents an Identity as returned by the DAPI Web API endpoint.
 * The Web API wrapper transforms raw responses into this camelCase format.
 */
export type DapiIdentityResponse = { identityId: string; 
/**
 * This field is often null in responses, as the public key hash is an input
 * parameter, not a property of the identity itself.
 */
publicKeyHash?: string | null; balance: string; revision: string; publicKeys?: DapiPublicKey[] }
/**
 * Represents a public key as returned by the DAPI Web API endpoint.
 * Note: Purpose and SecurityLevel are strings ("AUTHENTICATION", "MASTER", etc.)
 * not numeric codes, as per the Web API response format.
 */
export type DapiPublicKey = { purpose: string; securityLevel: string; keyType: string; data: string; dataB64: string; readOnly: boolean; disabledAt: string | null }
/**
 * Response for load_active_identity: returns identity data plus the active marker
 */
export type IActiveIdentityResponse = { activeIdentityId: string | null; identity: IIdentityData | null; identityCount: number }
export type IAppSettings = { network: string; theme: string; notifications: INotificationSettings; profile: IProfileSettings; activeIdentityId: string | null }
export type IAssetDefinition = { identityId: string; name: string; symbol: string; balance: string | null; assetId?: string | null; decimals: number | null; network: string | null }
export type ICommandResult<T> = { success: boolean; data: T | null; error: string | null }
export type IDiscoveredIdentity = { identityId: string; balance: string; identityIdx: number | null; dpnsUsername: string | null; keyType: string; discoveredAt: string }
export type IIdentityData = { identityId: string; username: string; balance: string; revision?: number; publicKeys: IIdentityPublicKey[]; identityIdx?: number | null; dpnsUsername?: string | null; isAuthenticated: boolean; createdAt?: string | null; publicKeyIds?: number[] | null }
export type IIdentityPublicKey = { id: number; type: string; purpose: number; securityLevel: number; data: string; readOnly: boolean; disabledAt: string | null }
export type ILicense = { success: boolean; identityId: string; txid: string; isPremium: boolean; createdAt: string; expiresAt: string; updatedAt: string | null }
export type IMnemonic = { seedPhrase: string }
export type INotificationSettings = { messages: boolean; mentions: boolean; contactRequests: boolean }
export type IPrivateKeyEntry = { identityId: string; keyId: number; purpose: number; securityLevel: number; keyType: string; privateKey: string; publicKey: string; createdAt: string; lastUsed: string }
export type IProfileSettings = { displayName: string; username: string; bio: string }
export type ISaveIdentityPayload = { identityId: string; username: string; balance: string; revision: number; publicKeys: any[]; identityIdx?: number | null; dpnsUsername?: string | null; createdAt?: string | null; publicKeyIds?: number[] | null; activeIdentityId?: string | null }
export type IUnifiedCommandResult = { success: boolean; error: string | null; payload: any | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
