
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async discoverAssets(identityId: string, network: string) : Promise<Result<IAssetDefinition[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_assets", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchIdentityTokens(identityId: string, network: string) : Promise<Result<IAssetDefinition[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_identity_tokens", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadAssets(identityId: string, network: string) : Promise<Result<IAssetDefinition[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_assets", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAssets(identityId: string, network: string, payload: IAssetDefinition[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_assets", { identityId, network, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAssets(network: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_assets", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hash160(input: number[]) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hash160", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async randomBytes(len: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("random_bytes", { len }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveIdentity(network: string, payload: ISaveIdentityPayload) : Promise<Result<IUnifiedCommandResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_identity", { network, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIdentity(network: string, identityId: string | null) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_identity", { network, identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveKeys(network: string, identityId: string, keys: IPrivateKeyEntry[]) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_keys", { network, identityId, keys }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadKeystore(network: string) : Promise<Result<any, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_keystore", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadLicense(identityId: string) : Promise<Result<ILicense | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_license", { identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveLicense(payload: ILicense) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_license", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLicense(identityId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_license", { identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshLicense(identityId: string) : Promise<Result<ILicense, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_license", { identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadMnemonic(network: string) : Promise<Result<IMnemonic | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_mnemonic", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveMnemonic(network: string, payload: IMnemonic) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_mnemonic", { network, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMnemonic(network: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mnemonic", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSettings() : Promise<Result<IAppSettings | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: IAppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateIdentityWithSdkData(network: string, identityId: string, publicKeys: IIdentityPublicKey[], revision: number, publicKeyIds: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_identity_with_sdk_data", { network, identityId, publicKeys, revision, publicKeyIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIdentityPublicKeys(network: string, identityId: string) : Promise<Result<IIdentityPublicKey[] | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_identity_public_keys", { network, identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIdentityPublicKeys(network: string, identityId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_identity_public_keys", { network, identityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dapiRequest(method: string, params: Partial<{ [key in string]: JsonValue }>, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dapi_request", { method, params, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dapiRequestArray(method: string, paramsArray: JsonValue[], network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dapi_request_array", { method, paramsArray, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPosts(dataContractId: string, documentType: string, whereClause: JsonValue | null, orderBy: JsonValue | null, limit: number | null, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_posts", { dataContractId, documentType, whereClause, orderBy, limit, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIdentityInfo(identityId: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_identity_info", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIdentityBalance(identityId: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_identity_balance", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIdentityById(identityId: string, network: string | null) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_identity_by_id", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenBalances(identityId: string, tokenIds: string[], network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_balances", { identityId, tokenIds, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveDpnsName(username: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_dpns_name", { username, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpnsUsername(identityId: string, network: string | null) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dpns_username", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpnsUsernames(identityId: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dpns_usernames", { identityId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlatformStatus(network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_platform_status", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIdentitiesBalances(identityIds: string[], network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_identities_balances", { identityIds, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDataContractInfo(contractId: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_data_contract_info", { contractId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenContractInfo(contractId: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_contract_info", { contractId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTokenStatuses(tokenIds: string[], network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token_statuses", { tokenIds, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTotalSupply(tokenId: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_total_supply", { tokenId, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentEpoch(network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_epoch", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTotalCreditsInPlatform(network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_total_credits_in_platform", { network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIdentityByPublicKeyHash(publicKeyHash: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_identity_by_public_key_hash", { publicKeyHash, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIdentityByNonUniquePublicKeyHash(publicKeyHash: string, network: string | null) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_identity_by_non_unique_public_key_hash", { publicKeyHash, network }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type IAppSettings = { network: string; theme: string; notifications: INotificationSettings; profile: IProfileSettings; activeIdentityId: string | null }
export type IAssetDefinition = { identityId: string; name: string; symbol: string; balance: string | null; assetId?: string | null; decimals: number | null; network: string | null }
export type IDiscoveredIdentity = { identityId: string; balance: string; identityIdx: number | null; dpnsUsername: string | null; keyType: string; discoveredAt: string }
export type IIdentityData = { identityId: string; username: string; balance: string; revision?: number; publicKeys: IIdentityPublicKey[]; identityIdx?: number | null; dpnsUsername?: string | null; isAuthenticated: boolean; createdAt?: string | null; publicKeyIds?: number[] | null }
export type IIdentityPublicKey = { id: number; type: string; purpose: number; securityLevel: number; data: string; readOnly: boolean; disabledAt: string | null }
export type ILicense = { success: boolean; identityId: string; txid: string; isPremium: boolean; createdAt: string; expiresAt: string; updatedAt: string | null }
export type IMnemonic = { seedPhrase: string }
export type INotificationSettings = { messages: boolean; mentions: boolean; contactRequests: boolean }
export type IPrivateKeyEntry = { identityId: string; keyId: number; purpose: number; securityLevel: number; keyType: string; privateKey: string; publicKey: string; createdAt: string; lastUsed: string }
export type IProfileSettings = { displayName: string; username: string; bio: string }
export type ISaveIdentityPayload = { identityId: string; username: string; balance: string; revision: number; publicKeys: any[]; identityIdx?: number | null; dpnsUsername?: string | null; createdAt?: string | null; publicKeyIds?: number[] | null; activeIdentityId?: string | null }
export type IUnifiedCommandResult = { success: boolean; error: string | null; payload: any | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
